fixtures:
  repositories:
    stdlib: "git://github.com/puppetlabs/puppetlabs-stdlib.git"
    mysql: "https://github.com/example42/puppet-mysql"
    user:  "https://github.com/example42/puppet-user"
    stdmod: "git://github.com/stdmod/stdmod.git"
    nginx: "git://github.com/netmanagers/puppet-nginx.git"
    apache: "git://github.com/example42/puppet-apache.git"
    php5fpm: "git://github.com/zertico/puppet-php5fpm.git"	
    puppi:  "git://github.com/example42/puppi.git" 
  symlinks:
    deploy_php: "#{source_dir}"
