name          'puppet-deploy_php'
version       '0.0.5'
source        'UNKNOWN'
author        'puppet'
license       'Apache License, Version 2.0'
summary       'This module installs and manages deploy_php'
description   'UNKNOWN. Based on stdmod/puppet-skeleton-standard 0.0.5.'
project_page  'UNKNOWN'
dependency    'puppetlabs/stdlib'
dependency    'example42/stdmod'
